<?xml version="1.0"?>
<robot xmlns:xacro='http://www.ros.org/wiki/xacro'>
    <!-- 引入惯性计算的xacro文件 -->
    <xacro:include filename="$(find robot_description)/urdf/fishbot/common_inertia.xacro"/>
    
    <xacro:macro name="base_xacro" params="length radius">
        <!-- 虚拟部件 机器人底盘 -->
        <link name="base_footprint"/>
        
        <link name="base_link">
        <!-- 部件的外观描述 -->
            <visual>
                <!-- 基于本身几何中心的偏移量和旋转量 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>

                <!-- 形状 -->
                <geometry>
                    <!-- 圆柱体 -->
                    <cylinder radius="${radius}"  length="${length}"/>
                </geometry>

                <!-- 颜色 -->
                <material name="white">
                    <!-- 最后一个值是透明度，1表示不透明 -->
                    <color rgba="1 1 1 0.5"/>
                </material>
            </visual>

            <!-- 碰撞体 -->
            <collision>
                <!-- 基于本身几何中心的偏移量和旋转量 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>

                <!-- 形状 -->
                <geometry>
                    <!-- 圆柱体 -->
                    <cylinder radius="${radius}"  length="${length}"/>
                </geometry>

                <!-- 颜色 -->
                <material name="white">
                    <!-- 最后一个值是透明度，1表示不透明 -->
                    <color rgba="1 1 1 0.5"/>
                </material>
            </collision>

            <!-- 惯性属性 -->
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}" />
        </link>

        <joint name="joint_name" type="fixed">
            <!-- 连接的父部件 -->
            <parent link="base_footprint"/>
            <!-- 连接的子部件 -->
            <child link="base_link"/>
            <!-- 基于父部件的偏移量和旋转量 -->
            <origin xyz="0.0 0.0 ${length/2+0.032-0.001}" rpy="0.0 0.0 0.0"/>
        </joint>

    </xacro:macro>

</robot>